### ISSUE TITLE
is there typescript types for this package ?

### ISSUE THREAD

**Issue by anver** [known-css/known-css-properties#135]
Is there a typescript @types package available for this awesome compilation ?

**Comment by vio** [comment]
hi @anver! No `@types`or type definitions available atm, though a PR will be welcome ;)

**Comment by vio** [comment]
added on https://github.com/known-css/known-css-properties/commit/9f47458f0f15efbe76819be54e2a6329c767dbba, released on https://github.com/known-css/known-css-properties/releases/tag/v0.24.0
