### ISSUE TITLE
Add `animation-timeline` property

### ISSUE THREAD

**Issue by renato-bohler** [known-css/known-css-properties#160]
Hey there!

The `animation-timeline` property has been shipped in Chrome 115 (latest) and is still not being exported as a known property by this library. Here's the spec for `animation-timeline`: https://drafts.csswg.org/css-animations-2/#animation-timeline

Are there any plans to add it?

The initial context is here: https://github.com/stylelint/stylelint/issues/7088

Thank you!

**Comment by vio** [comment]
Hi @renato-bohler, thank you for creating the issue!

It is on my list to gather the latest browser changes, hopefully I will be able to release a new version this week.

**Comment by renato-bohler** [comment]
Nice, I'll keep an eye on it. Thanks for your work!

**Comment by vio** [comment]
Added and released as part of `0.28.0`:

https://github.com/known-css/known-css-properties/pull/161/files#diff-9753e0d2f65dd443cfd08f24e8a840cbfc54ad301944e2d12bb5998e527237d2R63
