### ISSUE TITLE
Reads CSS properties and values from the browser source code

### ISSUE THREAD

**Issue by yisibl** [known-css/known-css-properties#162]
This is a very interesting project.

I haven't found a way to automatically update the CSS with new properties though, could you consider reading from the browser source code and automatically generating the appropriate JSON file?

For example, Chromium's CSS data definitions are here: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5

**Comment by vio** [comment]
Thank you @yisibl! 

 > I haven't found a way to automatically update the CSS with new properties though, could you consider reading from the browser source code and automatically generating the appropriate JSON file?

That might work for some browsers, but when I created the package, I was looking for a way to extract from all browsers(Safari, Firefox, Samsung Browser, etc). 

The current workflow requires loading a particular URL that collects window.getComputedStyle / document.body.style, normalizes the names, and sends them to a firestore database. Every other month, I run a script that dumps the data and generates the JSON files. I am planning to open-source the scripts, though I haven't managed to do it yet.

Is the package missing any properties?

**Comment by vio** [comment]
Feel free to re-open or open a new issue for missing properties (just released the latest - https://github.com/known-css/known-css-properties/releases/tag/v0.29.0)
